// <auto-generated />
namespace Proyecto_LibreriaRincondelQuijote.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddCantidadToHistorialCompra : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCantidadToHistorialCompra));
        
        string IMigrationMetadata.Id
        {
            get { return "202411250723500_AddCantidadToHistorialCompra"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
